### ISSUE TITLE
Return args as list

### ISSUE THREAD

**Issue by HannahBrown** [jwg4/flask-selfdoc#54]
When using the generate() method and there are no arguments, args is a list: 
```
{
	'methods': ['OPTIONS', 'POST'],
	'rule': '/auth',
	'endpoint': 'auth',
	'docstring': None,
	'args': ['None'],
	'defaults': None,
	'location': {
		'filename': '',
		'line': 0
	}
}
```
However, if there are arguments, args is a set:
```
{
	'methods': ['GET', 'HEAD', 'OPTIONS'],
	'rule': '/user/<user>',
	'endpoint': 'view_user_username',
	'docstring': None,
	'args': {'user'},
	'defaults': None,
	'location': {	
		'filename': '',
		'line': 0
	}
}
```
Sets are not valid JSON, and using jsonify(auto.generate()) (as shown in the documentation) results in: 
```
TypeError: Object of type set is not JSON serializable
```

**Comment by jwg4** [comment]
hi, sorry for not looking at this! the notification got lost.

**Comment by jwg4** [comment]
This is a bug, working on a fix.

**Comment by jwg4** [comment]
Hi @HannahBrown 

I realize you might not be waiting for this behavior to be fixed any more! Sorry for the monstrous delay.

In the new version 1.3.0, it should be working correctly. However note that using `autodoc.json()` will probably work better than doing `jsonify(autodoc.generate())`. The former uses a data structure specifically designed to have a good serialization, whereas the latter just serializes the structure designed for the HTML template.

Thanks for reporting this bug!
