### ISSUE TITLE
Jinja dependency

### ISSUE THREAD

**Issue by sergiokessler** [jwg4/flask-selfdoc#69]
Jinja2 dependency should be added so is automatically pulled

**Comment by jwg4** [comment]
The incompatibility between certain versions of Flask and certain versions of Jinja appears to have been an error by @davidism, the maintainer of both projects, who doubled down on his error by explaining to multiple people that he had done nothing wrong and that it was their own fault for not pinning specific versions. I didn't come to a clear understanding of what library maintainers should do, other than change their deps to only support more recent Flask versions.

I believe that he went on to close and delete all the bug reports and discussions about this common issue on both github projects. I was surprised by a lot of his behavior around this, particularly as he seems to be the principal maintainer of these two excellent projects.

I have no current plans to untangle this nonsense, but I will take a patch if someone else wants to, providing there is a clear explanation of why it solves the problem and maximizes compatibility of Flask-Selfdoc with Flask and Python versions.

**Comment by sergiokessler** [comment]
Sorry to come late to this, but no, Jinja2 is not a dependency of Flask (and should not be IMO).
For example, if you use Flask for developing an API, you don't need Jinja2 at all.

**Comment by jwg4** [comment]
Jinja2 certainly is a dependency of Flask.

**Comment by skessler-incucai** [comment]
hmm, I can assure you I'm using flask with no jinja installed just fine (I installed it because of selfdoc, but later uninstalled both things)

**Comment by jwg4** [comment]
Yes, that's not the definition of a dependency.
